<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>13.0</LangVersion>
    <AssemblyTitle>ScrollableFieldEditors</AssemblyTitle>
    <Company>Nytra</Company>
    <Product>ScrollableFieldEditors</Product>
    <Copyright>Copyright © Nytra 2025</Copyright>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(ResonitePath)'==''">
    <ResonitePath>$(MSBuildThisFileDirectory)Resonite/</ResonitePath>
    <ResonitePath Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')">C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath>
    <ResonitePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')">$(HOME)/.steam/steam/steamapps/common/Resonite/</ResonitePath>
    <ResonitePath Condition="Exists('R:\SteamLibrary\steamapps\common\Resonite\')">R:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
    <ResonitePath Condition="Exists('G:\SteamLibrary\steamapps\common\Resonite\')">G:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony-Net9">
      <HintPath>$(ResonitePath)rml_libs\0Harmony-Net9.dll</HintPath>
    </Reference>
    <Reference Include="Elements.Core, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ResonitePath)Elements.Core.dll</HintPath>
    </Reference>
    <Reference Include="FrooxEngine, Version=2024.8.5.1341, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ResonitePath)FrooxEngine.dll</HintPath>
    </Reference>
    <Reference Include="Renderite.Shared">
      <HintPath>$(ResonitePath)Renderite.Shared.dll</HintPath>
    </Reference>
    <Reference Include="ResoniteModLoader, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ResonitePath)Libraries\ResoniteModLoader.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ResonitePath)rml_mods" />
    <Message Text="Copied $(TargetFileName) to $(ResonitePath)rml_mods" Importance="high" />
  </Target>
</Project>